AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31


Parameters:
    AppName:
        Type: String
        Description: Name of the application
        Default: 'kotwarden'
    ProfileName:
        Type: String
        Description: Name of the application
        Default: 'config'
    Environment:
        Type: String
        Description: Environment
        Default: 'prod'

Resources:
    KotWardenHttpApi:
        Type: AWS::Serverless::HttpApi
        Properties:
            StageName: $default
            DefaultRouteSettings:
                ThrottlingBurstLimit: 5
                ThrottlingRateLimit: 10
    KotWardenFunction:
        Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
        Properties:
            CodeUri: .
            FunctionName: !Sub KotWarden-Handle
            Handler: com.ivyxjc.kotwarden.Server::handleRequest
            Runtime: java11
            Timeout: 15
            Tracing: Active
            Architectures:
                - arm64
            MemorySize: 512
            Policies:
                - AmazonDynamoDBFullAccess
                -   Version: '2012-10-17'
                    Statement:
                        -   Effect: Allow
                            Action:
                                - appconfig:GetConfiguration
                                - appconfig:GetLatestConfiguration
                                - appconfig:GetHostedConfigurationVersion
                                - appconfig:StartConfigurationSession
                            Resource:
                                -   Fn::Join:
                                        - ''
                                        -   - 'arn:aws:appconfig:*:*:application/'
                                            -   Ref: AppConfigLambdaApplication
                                -   Fn::Join:
                                        - ''
                                        -   - 'arn:aws:appconfig:*:*:application/'
                                            -   Ref: AppConfigLambdaApplication
                                            - '/configurationprofile/'
                                            -   Ref: AppConfigLambdaConfigurationProfile
                                -   Fn::Join:
                                        - ''
                                        -   - 'arn:aws:appconfig:*:*:application/'
                                            -   Ref: AppConfigLambdaApplication
                                            - '/environment/'
                                            -   Ref: AppConfigLambdaEnvironment
                                -   Fn::Join:
                                        - ''
                                        -   - 'arn:aws:appconfig:*:*:application/'
                                            -   Ref: AppConfigLambdaApplication
                                            - '/configurationprofile/*/hostedconfigurationversion/*'
                                -   Fn::Join:
                                        - ''
                                        -   - 'arn:aws:appconfig:*:*:application/'
                                            -   Ref: AppConfigLambdaApplication
                                            - '/environment/'
                                            -   Ref: AppConfigLambdaEnvironment
                                            - '*/configuration/*'
            Events:
                ApiEvent:
                    Type: HttpApi
                    Properties:
                        ApiId: !Ref 'KotWardenHttpApi'
                        Method: ANY
                        Path: /{proxy+}
                        TimeoutInMillis: 5000
                ScheduleEvent:
                    Type: Schedule
                    Properties:
                        Name: Kotwarden-Schedule
                        Enabled: true
                        Schedule: "rate(5 minutes)"

    AppConfigLambdaApplication:
        Type: 'AWS::AppConfig::Application'
        Properties:
            Name: !Ref AppName
    AppConfigLambdaEnvironment:
        Type: 'AWS::AppConfig::Environment'
        Properties:
            Name: !Ref Environment
            ApplicationId: !Ref AppConfigLambdaApplication
    AppConfigLambdaConfigurationProfile:
        Type: 'AWS::AppConfig::ConfigurationProfile'
        Properties:
            Name: !Ref ProfileName
            ApplicationId: !Ref AppConfigLambdaApplication
            LocationUri: hosted
    AppConfigLambdaDeploymentStrategy:
        Type: AWS::AppConfig::DeploymentStrategy
        Properties:
            Name: !Ref AppName
            DeploymentDurationInMinutes: 0
            FinalBakeTimeInMinutes: 1
            GrowthFactor: 100
            GrowthType: LINEAR
            ReplicateTo: NONE