AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
    Cipher:
        Type: AWS::DynamoDB::Table
        Properties:
            TableName: resource
            AttributeDefinitions:
                -   AttributeName: PK
                    AttributeType: S
                -   AttributeName: SK
                    AttributeType: S
                -   AttributeName: Folder
                    AttributeType: S
                -   AttributeName: Email
                    AttributeType: S
            KeySchema:
                -   AttributeName: PK
                    KeyType: HASH
                -   AttributeName: SK
                    KeyType: RANGE
            ProvisionedThroughput:
                ReadCapacityUnits: 1
                WriteCapacityUnits: 1
            GlobalSecondaryIndexes:
                -   IndexName: "Email-Index"
                    KeySchema:
                        -   AttributeName: Email
                            KeyType: HASH
                    Projection:
                        ProjectionType: ALL
                    ProvisionedThroughput:
                        ReadCapacityUnits: 1
                        WriteCapacityUnits: 1
                -   IndexName: "PK-Folder-Index"
                    KeySchema:
                        -   AttributeName: PK
                            KeyType: HASH
                        -   AttributeName: Folder
                            KeyType: RANGE
                    Projection:
                        ProjectionType: KEYS_ONLY
                    ProvisionedThroughput:
                        ReadCapacityUnits: 1
                        WriteCapacityUnits: 1
                -   IndexName: "Folder-SK-Index"
                    KeySchema:
                        -   AttributeName: Folder
                            KeyType: HASH
                        -   AttributeName: SK
                            KeyType: RANGE
                    Projection:
                        ProjectionType: ALL
                    ProvisionedThroughput:
                        ReadCapacityUnits: 1
                        WriteCapacityUnits: 1
    DeviceTable:
        Type: AWS::DynamoDB::Table
        Properties:
            TableName: device
            AttributeDefinitions:
                -   AttributeName: Id
                    AttributeType: S
                -   AttributeName: RefreshToken
                    AttributeType: S
            KeySchema:
                -   AttributeName: Id
                    KeyType: HASH
            TimeToLiveSpecification:
                AttributeName: TTL
                Enabled: true
            ProvisionedThroughput:
                ReadCapacityUnits: 1
                WriteCapacityUnits: 1
            GlobalSecondaryIndexes:
                -   IndexName: "RefreshToken-Index"
                    KeySchema:
                        -   AttributeName: RefreshToken
                            KeyType: HASH
                    Projection:
                        ProjectionType: ALL
                    ProvisionedThroughput:
                        ReadCapacityUnits: 1
                        WriteCapacityUnits: 1
    UserOrganizationTable:
        Type: AWS::DynamoDB::Table
        Properties:
            TableName: user_organization
            AttributeDefinitions:
                -   AttributeName: UserId
                    AttributeType: S
                -   AttributeName: OrganizationId
                    AttributeType: S
            KeySchema:
                -   AttributeName: UserId
                    KeyType: HASH
                -   AttributeName: OrganizationId
                    KeyType: RANGE
            ProvisionedThroughput:
                ReadCapacityUnits: 1
                WriteCapacityUnits: 1

#    Cipher:
#        Type: AWS::DynamoDB::Table
#        Properties:
#            TableName: cipher
#            AttributeDefinitions:
#                -   AttributeName: Id
#                    AttributeType: S
#                -   AttributeName: Owner
#                    AttributeType: S
#            KeySchema:
#                -   AttributeName: Id
#                    KeyType: HASH
#                -   AttributeName: Owner
#                    KeyType: RANGE
#            ProvisionedThroughput:
#                ReadCapacityUnits: 1
#                WriteCapacityUnits: 1
#            GlobalSecondaryIndexes:
#                -   IndexName: "Owner-Index"
#                    KeySchema:
#                        -   AttributeName: Owner
#                            KeyType: HASH
#                    Projection:
#                        ProjectionType: ALL
#                    ProvisionedThroughput:
#                        ReadCapacityUnits: 1
#                        WriteCapacityUnits: 1
#    Folder:
#        Type: AWS::DynamoDB::Table
#        Properties:
#            TableName: folder
#            AttributeDefinitions:
#                -   AttributeName: Id
#                    AttributeType: S
#                -   AttributeName: UserId
#                    AttributeType: S
#            KeySchema:
#                -   AttributeName: UserId
#                    KeyType: HASH
#                -   AttributeName: Id
#                    KeyType: RANGE
#            ProvisionedThroughput:
#                ReadCapacityUnits: 1
#                WriteCapacityUnits: 1