name: webapi-build
on:
    push:
        branches:
            - develop

    workflow_dispatch:

jobs:
    webapi-build:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
                name: checkout HEAD
                if: ${{ ! github.event.inputs.tag }}

            -   name: Set up JDK 11
                uses: actions/setup-java@v1
                with:
                    java-version: 11
            -   uses: aws-actions/setup-sam@v1

            -   name: Cache Gradle packages
                uses: actions/cache@v3
                with:
                    path: ~/.gradle/caches
                    key: ${{ runner.os }}-${{ hashFiles('*.gradle.kts') }}

            -   name: Configure AWS credentials
                uses: aws-actions/configure-aws-credentials@v1
                with:
                    aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
                    aws-secret-access-key: ${{ secrets.AWS_ACCESS_SECRET }}
                    aws-region: us-west-2

            -   run: sam build
            -   run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset